'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FerreSoft.UI.WF.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property Brisbanetanks_Tools_Hand_Drill_Machine() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Brisbanetanks_Tools_Hand_Drill_Machine", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property Brisbanetanks_Tools_Wrench() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Brisbanetanks_Tools_Wrench", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_window() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_window", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property construction_and_tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("construction_and_tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hardware() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hardware", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property Pixelkit_Swanky_Outlines_08_Wrench() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Pixelkit_Swanky_Outlines_08_Wrench", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property Rob_Sanders_Gear_Adjustable_Wrench() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Rob_Sanders_Gear_Adjustable_Wrench", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screwdriver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screwdriver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sound4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sound4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spatula() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spatula", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property tools() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tools", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property window() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
